### ISSUE TITLE
not an issue :)

### ISSUE THREAD

**Issue by Ken5998** [kylierst/MSO_E5_Dev_AutoRenew_REVISION_2#1]
On my forked version, I have fixed the skip of the jobs changing the line 20 with the following

if: (github.event.repository.owner.id == github.event.sender.id) || ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}  # Self-ordered start

I have also done some minor changes to improve the yml

https://github.com/Ken5998/MSO_E5_Dev_AutoRenew_REVISION_2

**Comment by kylierst** [comment]
oh that's a nice touch. I was trying to fix that too but I had no time. Thanks for sharing ur fix!
